### ISSUE TITLE
Incorrect Cursor example / implementation

### ISSUE THREAD

**Issue by ivarref** [tonsky/extend-clj#1]
Hi

And thank you @tonsky for an interesting and promising library!

I noticed that the following will "spin" forever, i.e. `compare-and-set!` will re-try forever:

```clojure
(let [*missing-cursor (->Cursor (atom {}) [:missing])]
  (is (= [nil 1] (swap-vals! *missing-cursor (fnil inc 0))))) ; will spin forever
```

I fixed it like this:

```clojure
(deftype-atom Cursor [*atom path]
  (deref-impl [this]
    (get-in @*atom path))
  (compare-and-set-impl [this oldv newv]
    (compare-and-set!
      *atom
      (let [*atm @*atom]
        (if (and (nil? oldv) (= ::none (get-in *atm path ::none)))
        *atm
        (assoc-in *atm path oldv)))
      (assoc-in @*atom path newv)))

  #?@(:clj [clojure.lang.Counted
            (count [_] 7)]
     :cljs [ICounted
            (-count [_] 7)]))
```

Not 100% sure that is correct though. What do you think? Is there some edge case that this will fail to handle?

I think it also would be great if the Cursor type would be included in the core so that there is no need to re-implement/copy it.

Thanks and kind regards!

**Comment by tonsky** [comment]
Thanks! Updated README
